site_name: 可爱奶龙数学培训

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
  logo: assets/images/nailoong.webp
  favicon: assets/images/nailoong.webp
  palette:
    # 浅色模式
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white         
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # 深色模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - abbr
  - footnotes
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption

extra_css:
  - https://cdn.jsdelivr.net/npm/katex@0.16.7/dist/katex.min.css
  - https://cdn.jsdelivr.net/npm/jsxgraph/distrib/jsxgraph.css

extra_javascript:
  - javascripts/katex.js
  - https://cdn.jsdelivr.net/npm/katex@0.16.7/dist/katex.min.js
  - https://cdn.jsdelivr.net/npm/katex@0.16.7/dist/contrib/auto-render.min.js
  - https://unpkg.com/mermaid@10/dist/mermaid.min.js
  - javascripts/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://cdn.jsdelivr.net/npm/jsxgraph/distrib/jsxgraphcore.js
  - https://cdnjs.cloudflare.com/ajax/libs/mathjs/11.8.0/math.js

# plugins:
#   - encryptcontent:
#       global_password: "keainailong"
#       title_prefix: ""

plugins:
   - search
  #  - encryptcontent:
  #     global_password: "keainailong"
  #     title_prefix: ""
   - glightbox:
       touchNavigation: true
       loop: false
       effect: zoom
       slide_effect: slide
       width: 100%
       height: auto
       zoomable: true
       draggable: true
       skip_classes:
         - custom-skip-class-name
       auto_themed: false
       auto_caption: false
       caption_position: bottom
       background: white
       shadow: true
       manual: false


nav:
  - "首页": index.md
  - "教学安排": schedule.md
  - "Algebra":
    - "数与式":
      - "实数": number/real_number.md
    - "方程与不等式":
      - "整式方程&分式方程": equation/polynomial_rational_equation.md
      - "无理方程": equation/irrational_equation.md
      - "二元二次方程": equation/quadratic_equation_in_two_variables.md
      - "应用题": equation/word_problem.md
    - "函数":
      - "一次函数": function/linear_function.md
      - "二次函数": function/quadratic_function.md
      - "反比例函数": function/inverse_variation.md
      - "有理函数": function/rational_function.md
      - "指数函数": function/exponential_function.md
  - "Geometry":
    - "三角形":
      - "三角形重心": quad/triangle_centroid.md
    - "四边形":
      - "多边形": quad/polygon.md
      - "平行四边形": quad/parallelogram.md
      - "矩形": quad/rectangle.md
      - "菱形": quad/rhombus.md
      - "正方形": quad/square.md
  - "Statistics": 
    - "概率": probability/probability.md
  - "答案": ans/index.md
