site_name: 可爱奶龙数学培训

theme:
  name: material
  logo: assets/images/nailoong.webp
  favicon: assets/images/nailoong.webp
  palette:
    # 浅色模式
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white         
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # 深色模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - abbr
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.id/features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# plugins:
#   - encryptcontent:
#       global_password: "keainailong"
#       title_prefix: ""

plugins:
   - search
  #  - encryptcontent:
  #     global_password: "keainailong"
  #     title_prefix: ""
   - glightbox:
       touchNavigation: true
       loop: false
       effect: zoom
       slide_effect: slide
       width: 100%
       height: auto
       zoomable: true
       draggable: true
       skip_classes:
         - custom-skip-class-name
       auto_themed: false
       auto_caption: false
       caption_position: bottom
       background: white
       shadow: true
       manual: false


nav:
  - "首页 Homepage": index.md
  - "四边形 Quadrilateral":
    - "多边形 Polygon": quad/polygon.md
    - "平行四边形 Parallelogram": quad/parallelogram.md
    - "矩形 Rectangle": quad/rectangle.md
    - "菱形 Rhombus": quad/rhombus.md
    - "正方形 Square": quad/square.md
  - "答案 Answer Keys": answer_key/intro.md


 